Contributing guidelines
Interlisp/maiko pull request #165
Opened 2021-01-02 22:40 UTC by masinter

Please review and make suggestions. I started with one of the samples (Ruby on Rails) as recommended in GitHub.
Do we need different guidelines for Maiko and Medley?  Should we put the approval policy here or elsewhere (I don't think we have consensus yet on that).
This is one of the steps for https://github.com/Interlisp/medley/issues/111

2021-01-03 02:23 UTC, waywardmonkeys requested changes

2021-01-03 02:23 UTC, waywardmonkeys commented on CONTRIBUTING.md
> +# How to contribute to Medley Interlisp
Since this is in the Maiko repository, I feel like this should have some indication here.

2021-01-03 02:23 UTC, waywardmonkeys commented on CONTRIBUTING.md
> +* Open a new GitHub pull request with the patch
Missing a period at the end of this. Should probably also link 'GitHub pull request' to https://github.com/Interlisp/maiko/pulls

2021-01-03 04:52 UTC, nbriggs commented
I think we may need to have separate versions of the file for the Lisp side and the emulator code.
If you're reporting a problem in Lisp (or you don't know whether it's a bug in the Lisp code or the emulator) you should include which sysout you're running in, and the emulator version (we should make this retrievable from the Common Lisp environment info), and the OS and processor architecture (so we know big-/little- endian -- Solaris 11 could be either; 32- or 64-bit).  On the Lisp side, the LOADEDFILELST and FILELST have useful info.

2021-01-03 21:06 UTC, masinter commented
@nbriggs I will propose some[issue templates](https://docs.github.com/en/free-pro-team@latest/github/building-a-strong-community/configuring-issue-templates-for-your-repository) for reporting errors that will ask for appropriate information

2021-01-03 21:08 UTC, nbriggs commented
OK.   Have a look at https://www.freebsd.org/doc/en_US.ISO8859-1/articles/problem-reports/article.html as well, it's not *directly* applicable to our code but it makes a lot of good points.

2021-01-03 21:10 UTC, nbriggs commented
Also -- https://github.com/ncovercash/reporting-bugs-effectively/blob/master/ENGLISH.md

2021-01-03 22:42 UTC, masinter commented
I just read about setting issue templates and other community guidelines for the whole Interlisp organization by setting up a .github repo, and I'm going to do that.

2021-01-03 22:42 UTC, closed without merging

2021-01-04 00:31 UTC, nbriggs commented
OK, could you spell check the document before committing it?