Support for netbsd
Interlisp/maiko pull request #464
Opened 2023-03-29 04:30 UTC by mldulaney

Adds support for netbsd

2023-03-29 04:59 UTC, waywardmonkeys commented
Does the cmake build system work here without changes?

2023-03-29 06:24 UTC, nbriggs requested changes
If you add the “init” version of the makefile fragment as well then it will enable doing loadups on netbsd also.  See the FreeBSD equivalent…

2023-04-18 01:28 UTC, mldulaney commented
> Does the cmake build system work here without changes?

It did not seem to make all binaries



> If you add the “init” version of the makefile fragment as well then it will enable doing loadups on netbsd also. See the FreeBSD equivalent…

Got that bit working, too, and I'll update my PR shortly.

2023-04-18 01:33 UTC, nbriggs commented
@mldulaney - the cmake default is to make only the binaries you need to run an existing sysout, so `lde` and `ldex`.  Given that we're not checking in sysout files these days it would make sense to have the CMake targets include `ldeinit` as well.

2025-07-04 16:51 UTC, mldulaney commented
using cmake worked.  closing.

2025-07-04 16:51 UTC, closed without merging